"""
Settings file for decentralized devstack
"""

from os import environ

from .production import *  # pylint: disable=wildcard-import, unused-wildcard-import

AWS_DEFAULT_ACL = None
AWS_SES_REGION_NAME = environ.get('AWS_SES_REGION_NAME', AWS_SES_REGION_NAME)
AWS_SES_REGION_ENDPOINT = environ.get('AWS_SES_REGION_ENDPOINT', AWS_SES_REGION_ENDPOINT)
AWS_ACCESS_KEY_ID = environ.get('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
AWS_SECRET_ACCESS_KEY = environ.get('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)
AWS_SECURITY_TOKEN = environ.get('AWS_SECURITY_TOKEN', AWS_SECURITY_TOKEN)
AWS_QUERYSTRING_AUTH = environ.get('AWS_QUERYSTRING_AUTH', AWS_QUERYSTRING_AUTH)
AWS_STORAGE_BUCKET_NAME = environ.get('AWS_STORAGE_BUCKET_NAME', AWS_STORAGE_BUCKET_NAME)
AWS_S3_CUSTOM_DOMAIN = environ.get('AWS_S3_CUSTOM_DOMAIN', AWS_S3_CUSTOM_DOMAIN)